"use client";

import React, { useState } from 'react';

const SMS_TEST_API = '/api/sms/webhook';
const TWILIO_NUMBER = '+18775219907';

export default function SmsTestPage() {
  const [contractor, setContractor] = useState('');
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<{ from: 'contractor' | 'system'; text: string }[]>([]);
  const [loading, setLoading] = useState(false);

  const sendMessage = async () => {
    if (!input || !contractor) return;
    setMessages((msgs) => [...msgs, { from: 'contractor', text: input }]);
    setLoading(true);
    try {
      const formData = new FormData();
      formData.append('From', contractor);
      formData.append('Body', input);
      const res = await fetch(SMS_TEST_API, {
        method: 'POST',
        body: formData,
      });
      const text = await res.text();
      // Try to extract the message from the TwiML XML
      const match = text.match(/<Message>([\s\S]*?)<\/Message>/i);
      const reply = match ? match[1].trim() : text;
      setMessages((msgs) => [...msgs, { from: 'system', text: reply }]);
    } catch (err) {
      setMessages((msgs) => [...msgs, { from: 'system', text: 'Error sending message.' }]);
    }
    setInput('');
    setLoading(false);
  };

  return (
    <div style={{ maxWidth: 500, margin: '40px auto', padding: 24, border: '1px solid #ccc', borderRadius: 8 }}>
      <h2>SMS Conversation Test</h2>
      <div style={{ color: '#555', marginBottom: 12 }}>
        <b>Twilio number:</b> <span style={{ color: '#007bff' }}>{TWILIO_NUMBER}</span>
      </div>
      <div style={{ marginBottom: 16 }}>
        <input
          type="text"
          placeholder="Contractor number (e.g. +15555555555)"
          value={contractor}
          onChange={e => setContractor(e.target.value)}
          style={{ width: '100%', marginBottom: 8, padding: 8 }}
        />
      </div>
      <div style={{ minHeight: 200, background: '#fafafa', padding: 12, borderRadius: 4, marginBottom: 16, border: '1px solid #eee' }}>
        {messages.length === 0 && <div style={{ color: '#888' }}>No messages yet.</div>}
        {messages.map((msg, i) => (
          <div key={i} style={{ textAlign: msg.from === 'contractor' ? 'right' : 'left', margin: '8px 0' }}>
            <span style={{
              display: 'inline-block',
              background: msg.from === 'contractor' ? '#d1e7dd' : '#e2e3e5',
              color: '#222',
              borderRadius: 16,
              padding: '8px 14px',
              maxWidth: '80%',
              wordBreak: 'break-word',
            }}>{msg.text}</span>
          </div>
        ))}
      </div>
      <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
        <input
          type="text"
          placeholder="Type your message..."
          value={input}
          onChange={e => setInput(e.target.value)}
          style={{ flex: 1, padding: 8 }}
          onKeyDown={e => { if (e.key === 'Enter') sendMessage(); }}
          disabled={loading}
        />
        <button onClick={sendMessage} disabled={loading || !input || !contractor} style={{ padding: '8px 16px' }}>
          Send
        </button>
      </div>
      <div style={{ color: '#888', fontSize: 13 }}>
        <div>Reply as the contractor. System messages are autogenerated by your backend.</div>
        <div>All messages are simulated locally for debugging.</div>
      </div>
    </div>
  );
} 